name: AI News Digest

on:
  schedule:
    # Каждый день в 06:00 UTC = 09:00 по Нячангу (UTC+7)
    - cron: "0 6 * * *"
  workflow_dispatch:
    # Позволяет запустить вручную кнопкой в GitHub (Actions -> Run workflow)

jobs:
  send-digest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run digest script
        env:
         PROXYAPI_KEY: ${{ secrets.PROXYAPI_KEY }}
         TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
         TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
